spring:
  application:
    name: ByteCafe

    datasource:
      url: jdbc:mysql://ubuntu-server:3306/bytecafe
      username: bytecafe
      password: bytecafe
      driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis-plus:
    global-config:
      db-config:
        logic-delete-field: id_deleted # 全局逻辑删除字段名
        logic-delete-value: 1 # 逻辑已删除值
        logic-not-delete-value: 0 # 逻辑未删除值
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl